### ISSUE TITLE
Mac에서 config.ini 를 열 수 있는 app이 무엇인가요?!

### ISSUE THREAD

**Issue by Davidyeon** [leegeunhyeok/cyworld-bot#10]
안녕하세요?! 
저는 컴퓨터 프로그램에 대한 지식이 거의 없는데요, 싸이월드 사진 및 자료들을 쉽게 다운받을 수 있다고 해서 이렇게 문의 드립니다. 

사진으로 보여주신 순서대로 따라서 하고 있었는데, 
config.ini 를 열 수 있는 어플리케이션이 없다고 나오네요. 

저는 맥을 쓰고 있는데요, 어떤 어플리케이션을 쓰면 config.ini을 열 수 있을까요?!

**Comment by onitonitonito** [comment]
어떤 어플도  가능합니다. notepad++ 을 써보세요
https://www.google.com/search?q=download+notepad%2B%2B&oq=download+notepa&aqs=chrome.1.69i57j0l5.8503j0j7&sourceid=chrome&ie=UTF-8

**Comment by leegeunhyeok** [comment]
아무 텍스트 에디터로 파일을 열어주시면 됩니다 :)
