### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'delay'

### ISSUE THREAD

**Issue by howtextworks** [leegeunhyeok/cyworld-bot#13]
(2019-11-05 17:42:35.977639) - [INFO] 크롬 드라이버 로딩 중..
(2019-11-05 17:42:38.204755) - [INFO] 크롬 드라이버 로딩 완료
(2019-11-05 17:42:38.205356) - [INFO] 싸이월드 홈페이지 접속 중..
(2019-11-05 17:42:52.927189) - [SUCCESS] 싸이월드 홈페이지 접속 완료
(2019-11-05 17:42:52.928170) - [INFO] 로그인 시도 중..
(2019-11-05 17:43:17.907296) - [SUCCESS] 로그인 성공
(2019-11-05 17:43:17.907720) - [INFO] 마이 홈으로 이동 중..
(2019-11-05 17:43:27.339354) - [SUCCESS] 이동 완료
(2019-11-05 17:43:27.341797) - [INFO] 이미지 다운로드 작업 시작
Traceback (most recent call last):
  File "bot.py", line 246, in <module>
    .run(parser=parser, downloader=downloader)
  File "bot.py", line 190, in run
    self._chromedriver, cookie, parser_logger, self._delay)
TypeError: __init__() missing 1 required positional argument: 'delay'

위의 로그와 함께 봇이 종료됩니다.

**Comment by leegeunhyeok** [comment]
새로운 옵션값을 추가한 이후에 코드상에 오류가 있음을 확인했습니다.
