### ISSUE TITLE
드라이버 폴더가 어떤 폴더 말하는 건가요?

### ISSUE THREAD

**Issue by aiod01** [leegeunhyeok/cyworld-bot#14]
압축을 푼 크롬드라이버는 어디에 두어야 할 지 이해를 못 하여 질문합니다..

또한 config.ini 파일이 없는데 이전 어디에서 제가 잘 따르지 못한 부분이 있는 건가요?

**Comment by onitonitonito** [comment]
![image](https://user-images.githubusercontent.com/25020045/68442514-932ca700-0214-11ea-9c7b-0cf38759f76c.png)

logs 폴더는 제가 따로 만든겁니다. (다른 위치만 참조하시면 될 것 같네요.)
config.ini 는 README.md를 보시고 텍스트화일을 새로 만드셔도 될 것 같네요.

**Comment by leegeunhyeok** [comment]
@onitonitonito 님의 답변대로 소스코드의 driver 폴더에 드라이버 파일을 넣어두시면 됩니다.

config.ini 같은 경우에는 소스코드에 함께 포함되어있으나 삭제했더나 기타 문제로 인해 없는 경우 동일한 이름의 파일을 생성하신 후 설정 내용을 작성해주시면 됩니다.

설정 내용은 [여기](https://github.com/leegeunhyeok/cyworld-bot/blob/master/config.ini)에서 확인하실 수 있습니다.

감사합니다
