### ISSUE TITLE
"알 수 없는 오류가 발생했습니다"

### ISSUE THREAD

**Issue by ggg5438** [leegeunhyeok/cyworld-bot#20]
크롬 드라이버 로딩 완료
싸이월드 홈페이지 접속 중..
ERROR : ssl_client_socket_impl.cc(935) handshake failed
싸이월드 홈페이지 접속 완료
로그인 시도 중...
알수없는 오류가 발생했습니다
QThread::wait: Thread tried to wait on itself

로그가 이렇게 뜨고 작동이 안 됩니다.ㅠㅠ

**Comment by leegeunhyeok** [comment]
안녕하세요,정확한 로그 파악이 어려워 2가지 상황임을 유추하고 있습니다.

- SSL 인증서 오류
- 크롬 브라우저와 드라이버간의 오류

첫 번째의 경우 수정하여 배포될 예정이지만, 두 번째 경우일 수 있으니 크롬 브라우저의 버전과 드라이버 버전을 다시 확인해주시면 감사하겠습니다 :)
