### ISSUE TITLE
오류관련 문의

### ISSUE THREAD

**Issue by dawini** [leegeunhyeok/cyworld-bot#22]
![20200422_001008_1](https://user-images.githubusercontent.com/64090819/79882492-a97a9800-842d-11ea-8088-32b1fe9a6676.jpg)

한참 잘 되다가 갑자기 파란화면뜨면서 PC재부팅 되더니 싸이봇 다시 실행하면 안되요. 
싸이봇화면이 닫히고 저 검은화면만 남아서 더이상 진행이 안되네요. 
왜 이렇게 될까요?
그리고 사진파일이나 그외 글 파일들도 종료되기전  저장된건 제대로된 파일이 아니예요. 
다시 다른 폴더에 싸이봇을 다운받아 해봐도 안되네요.

**Comment by leegeunhyeok** [comment]
늦은 답변 죄송합니다.

오류 메시지를 확인해보니, 클릭 자동화 부분에서 잘못된 요소가 클릭되어 발생된 것으로 보입니다.
아래와 같은 사양의 PC에서 테스트 해본 결과 문제는 없었으나, 위와 같은 문제가 지속적으로 발생한다면, 아래의 사항을 확인해주세요

[ 테스트 사양 ]
- OS: Windows 10 Home 1903 (Build 18362.778)
- Chrome:  81.0.4044.129

[ 대처방법 ]
- 직접 싸이월드 홈페이지에 접속하여 로그인 확인
- 로그인 후 마이페이지로 이동 확인
- 별도의 팝업(비밀번호 변경 안내, 기타 공지사항 등)이 홈페이지에 존재하는지 확인

별다른 진척이 없을 경우 상세한 실행 환경을 기재해주세요.
감사합니다 :)
