### ISSUE TITLE
이거 지금 크롤링해도 저장 가능한가요?

### ISSUE THREAD

**Issue by donghee23** [leegeunhyeok/cyworld-bot#23]
싸이월드 이거 지금도 크롤링 되는건가요?

**Comment by leegeunhyeok** [comment]
안녕하세요, 답변 드립니다.


최근 싸이월드 서비스 종료 설과 더불어 서버 접속에 많은 장애가 발생하는 것을 확인했습니다.
(로그인 안됨, 게시물 보이지 않음 등)

크롤러가 아니더라도 직접 로그인 한 후 게시물을 확인해보면, 아무것도 보이지 않는 문제가 있습니다.
싸이월드 측의 장애 대응이나 기타 해결방안이 제시되어야 본 크롤러도 정상적으로 사용할 수 있을 것 같습니다.


현재로선 크롤러가 잘 동작한다고 하더라도, 싸이월드 서버에 문제가 존재하여 정상적인 사용이 어렵다는 답변을 드립니다 ㅜㅜ.
