### ISSUE TITLE
게시글의 내용도 파싱되면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by samslow** [leegeunhyeok/cyworld-bot#4]
먼저 만들어주셔서 감사합니다.

이미지가 잘 다운받아지네요.

실제로 사용 해 보니 게시글에 내용이 더 중심인 경우가 많더라구요.

혹시 이미지 폴더명을 posts로 변경하고 같은 파일명에 txt확장자로 파싱되게 해주는 기능을 추가 할 예정은 없으신가요?

감사합니다.

**Comment by leegeunhyeok** [comment]
게시물 내용도 텍스트로 저장할 수 있도록 페이지 구조 확인 후 기능 추가해보도록 하겠습니다

감사합니다 :)

**Comment by leegeunhyeok** [comment]
게시물 내용을 텍스트로 저장하는 기능이 새로 구현되었습니다.
posts 폴더 내에 이미지 파일명과 동일한 이름의 텍스트 파일로 저장됩니다.

![image](https://user-images.githubusercontent.com/26512984/68097919-0ecce200-fefd-11e9-8598-761dc7b2963d.png)

또한 제보된 문제점 수정/보완 작업도 이루어졌습니다.

감사합니다

**Comment by samslow** [comment]
와우 감사합니다.
