### ISSUE TITLE
의존 라이브러리 설치부터 막히는데 조금 자세한 설명을 받을 수 있을까요?

### ISSUE THREAD

**Issue by kyb444** [leegeunhyeok/cyworld-bot#7]
안녕하세요. 싸이월드 사진 백업을 찾던 중에 글을 보게 되었습니다.
제가 코딩 쪽을 잘 몰라서 그런지 4번 의존 라이브러리 설치부터 어떻게 해야 하는지 막혀서 문의드립니다. 

의존 라이브러리 설치에서 드라이브 폴더에 크롬드라이버 파일을 넣고 그 파일을 어떻게 실행해서 아래와 같은 명령어를 넣는 것일까요? 그다음에 필요한 기본 설정 및 실행 명령어도 어떻게 해야 하는지 몰라 문의드립니다.

제 컴퓨터 환경은 Mac OS입니다. 설명에서 적어주신 파이썬 등은 설치를 완료하였습니다.
혹여라도 시간이 허락된다면 답변 부탁드립니 :)

**Comment by leegeunhyeok** [comment]
크롬 드라이버 파일은 driver 폴더에 넣어두기만 하면 되며, 실행과 같은 추가적인 작업은 없습니다.

이후 소스코드가 있는 위치에서 터미널(윈도우의 경우 CMD)을 열어주시고, 터미널에서 의존 라이브러리 설치 명령어를 입력해주시면 됩니다!

터미널을 소스코드가 있는 위치에서 열기 위해서는 아래와 같이 진행해주시면 됩니다.

1. 터미널(혹은 CMD)실행
2. `cd 폴더명` 명령어로 폴더 이동
3. 2번 과정을 반복하여 소스코드가 있는 폴더로 이동
4. 가이드에 따라 명령어 입력

**Comment by kyb444** [comment]
@leegeunhyeok 상세한 설명 감사합니다 :) 저녁에 시도해보겠습니다!
