### ISSUE TITLE
[ERROR] 시간이 초과되었습니다

### ISSUE THREAD

**Issue by howtextworks** [leegeunhyeok/cyworld-bot#9]
(2019-11-04 09:58:06.543329) - [INFO] 크롬 드라이버 로딩 중..
(2019-11-04 09:58:08.673538) - [INFO] 크롬 드라이버 로딩 완료
(2019-11-04 09:58:08.674320) - [INFO] 싸이월드 홈페이지 접속 중..
(2019-11-04 09:58:23.120707) - [SUCCESS] 싸이월드 홈페이지 접속 완료
(2019-11-04 09:58:23.121136) - [INFO] 로그인 시도 중..
(2019-11-04 09:58:28.509315) - [ERROR] 시간이 초과되었습니다
시간이 초과되었다는 메시지와 함께 프로그램이 종료됩니다.  크롬 잘 열리고 열린 크롬에서 로그인되어 싸이 타임라인으로 넘어가는 것까지 확인됩니다만, 타임라인으로 넘어가기 전에 시간초과로 프로그램이 종료됩니다.
해외 거주하여 서버응답이 늦어서 그런걸까요? 해결방안 알려주시면 감사하겠습니다.

**Comment by leegeunhyeok** [comment]
타임라인으로 넘어가기 전에 시간초과 오류가 발생한것으로 보아 네트워크 상태가 불안정하여 시간 초과 오류가 발생한 것 같습니다.

기존 크롤러의 경우 대기시간은 5초로 고정되어있었으나 본 문제를 해결하기 위해 따로 config.ini 파일에 설정할 수 있도록 수정되었습니다.

```
[bot]
wait=5
```

기본값인 5를 적절한 값으로 설정하신 후 다시 시도해보세요(5초보다 더 대기할 수 있도록)
추가적인 문제가 있을경우 문의 부탁드립니다

감사합니다
